import { CheckCircle, AlertTriangle, Activity, Download } from "lucide-react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface PredictionResultProps {
  prediction: {
    prediction: string;
    confidence: number;
  };
}

function PredictionResult({ prediction }: PredictionResultProps) {
  const isHighRisk = prediction.confidence > 0.7;

  const downloadPDF = () => {
    const doc = new jsPDF();
    const dateTime = new Date().toLocaleString();
    const logoUrl = "https://i.postimg.cc/QCJM4mqq/allied-therapy.png"; // Replace with your logo URL

    // Add Header
    doc.setFillColor(230, 245, 255); // Light blue background
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(0, 51, 102); // Dark blue text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("LiverSCAN AI Report", 105, 15, { align: "center" });

    // Add Date
    doc.setFontSize(12);
    doc.text(`Date & Time: ${dateTime}`, 105, 25, { align: "center" });

    const pdfWidth = 355; // A4 width in points
    const logoWidth = 45; // Adjust width
    const logoHeight = 40; // Adjust height
    const xPos = (pdfWidth - logoWidth) / 2; // Centered X position
    const yPos = 0.1; // Top padding

    doc.addImage(logoUrl, "PNG", xPos, yPos, logoWidth, logoHeight);

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Liver Function Test", 105, 52, { align: "center" });
    

    autoTable(doc, {
      startY: 60,
      head: [["Investigation", "Result", "Reference Range"]],
      body: [
        ["Prediction:", prediction.prediction, "Normal / Abnormal"],
        ["Confidence Score:", `${(prediction.confidence * 100).toFixed(1)}%`, "25%-45%"],
        [
          "Assessment:",
          isHighRisk ? "Urgent Attention Required" : "Low Risk Assessment",
          "N/A",
        ],
        [
          "Recommendation:",
          isHighRisk
            ? "Immediate medical consultation is recommended."
            : "Maintain regular check-ups for optimal liver health.",
          "N/A",
        ],
      ],
      theme: "grid",
      headStyles: { fillColor: [180, 220, 255], textColor: [0, 51, 102] },
      bodyStyles: { textColor: [0, 0, 0] },
      styles: { fontSize: 12, cellPadding: 5, lineWidth: 0 }, // Hides borders
      didParseCell: function (data) {
        if (data.row.index === 2 && data.column.index === 1) { // "Assessment" row, second column
          if (data.cell.text[0] === "Urgent Attention Required") {
            data.cell.styles.textColor = [255, 0, 0]; // Red color
            data.cell.styles.fontStyle = "bold";
          } else if (data.cell.text[0] === "Low Risk Assessment") {
            data.cell.styles.textColor = [0, 128, 0]; // Green color
            data.cell.styles.fontStyle = "bold";
          }
        }
      },
    });
    

    // Footer
    doc.setTextColor(100);
    doc.setFontSize(10);
    doc.text(
      "This report is generated by LiverScan AI and is for informational purposes only.",
      105,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );

    doc.save("LiverScan_Result.pdf");
  };

  return (
    <div className="glass-effect rounded-xl shadow-xl p-8 mb-8 transform hover:scale-[1.01] transition-transform duration-300">
      <div className="flex items-center justify-center mb-6">
        {isHighRisk ? (
          <AlertTriangle className="h-16 w-16 text-red-500 animate-float" />
        ) : (
          <CheckCircle className="h-16 w-16 text-green-500 animate-float" />
        )}
      </div>

      <h2 className="text-2xl font-bold text-center text-gray-800 mb-6">
        Analysis Results
      </h2>

      <div className="space-y-6">
        <div className="bg-white/50 p-6 rounded-lg shadow-inner">
          <h3 className="text-sm font-medium text-gray-500 flex items-center">
            <Activity className="h-4 w-4 mr-2" />
            Prediction
          </h3>
          <p className="text-xl font-semibold text-gray-900 mt-2">
            {prediction.prediction}
          </p>
        </div>

        <div className="bg-white/50 p-6 rounded-lg shadow-inner">
          <h3 className="text-sm font-medium text-gray-500">Confidence Score</h3>
          <div className="mt-3">
            <div className="w-full bg-gray-200 rounded-full h-3">
              <div
                className={`h-3 rounded-full transition-all duration-1000 ${
                  isHighRisk ? "bg-red-500" : "bg-green-500"
                }`}
                style={{ width: `${prediction.confidence * 100}%` }}
              ></div>
            </div>
            <p className="mt-2 text-sm font-medium text-gray-700">
              {(prediction.confidence * 100).toFixed(1)}% Confidence
            </p>
          </div>
        </div>

        <div
          className={`p-6 rounded-lg shadow-inner ${
            isHighRisk ? "bg-red-50" : "bg-green-50"
          }`}
        >
          <h3
            className={`text-lg font-semibold mb-2 ${
              isHighRisk ? "text-red-800" : "text-green-800"
            }`}
          >
            {isHighRisk ? "Urgent Attention Required" : "Low Risk Assessment"}
          </h3>
          <p
            className={`text-sm ${
              isHighRisk ? "text-red-700" : "text-green-700"
            }`}
          >
            {isHighRisk
              ? "Based on the analysis, immediate medical consultation is recommended. Please contact your healthcare provider as soon as possible."
              : "The analysis suggests lower risk levels. However, maintaining regular check-ups and a healthy lifestyle is still important for your liver health."}
          </p>
        </div>
      </div>

      <button
        onClick={downloadPDF}
        className="mt-6 w-full flex items-center justify-center bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-lg transition duration-300"
      >
        <Download className="h-5 w-5 mr-2" />
        Download Report
      </button>
    </div>
  );
}

export default PredictionResult;
// Note: Ensure to install the required libraries using: